version: '3.8'
services:
  node:
    container_name: cont_node_app
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./app:/app
      - node_modules_vol:/app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"

volumes:
  node_modules_vol: